name: work_out
description: work out app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animations: ^2.0.3
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.0.1
  connectivity: ^3.0.6
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  delayed_display: ^2.0.0
  device_preview: ^1.1.0
  dio: ^5.5.0+1
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_windowmanager: ^0.2.0
  get: ^4.6.5
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.3
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: imgs/logo.png
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: imgs/logo.png
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: imgs/logo.png
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: imgs/logo.png
flutter_native_splash:
  color: "#232441"
  image: imgs/logo.png #background_image: "assets/background.png"

 
  android_12:
    color: "#232441"
    image: imgs/logo.png
  
  
  fullscreen: true
 
flutter:

  uses-material-design: true
  assets:
    - imgs/
 